// src/pages/Works/index.tsx
export const WorksPage = () => {
  return (
    <>
      <h1>Works</h1>

      <p>
        <b>Under Construction...</b>
      </p>

      <ul>
        <li>Software</li>
        <ul>
          <li>System Software</li>
          <ul>
            <li>OS</li>

            <li>Language Processor</li>
            <ul>
              <li>Compiler</li>
              <li>Interpreter</li>
              <li>Virtual Machine</li>
            </ul>

            <li>Middleware</li>
            <ul>
              <li>DBMS(MySQL, PostgreSQL, MongoDB, etc...)</li>
              <li>TCP/IP Software</li>
              <li>HTTP Server(Nginx, Apache HTTP Server)</li>
            </ul>
          </ul>

          <li>Application Software</li>
          <ul>
            <li>Web Application</li>
            <li>Mobile Application</li>
            <li>Cross Platform Application</li>
            <li>CLI Tools</li>
            <li>Others</li>
          </ul>
        </ul>

        <li>Hardware</li>
        <ul>
          <li>CPU(processor, micro processor)</li>
          <li>Storage Unit</li>
          <li>Input Unit</li>
        </ul>
      </ul>
    </>
  );
};

// src/routes/works/index.svelte
<svelte:head>
  <title>Works</title>
</svelte:head>

<h1>Works</h1>

<p><b>Under Construction...</b></p>

<!-- ref: https://nukopy.notion.site/nukopy/Wiki-for-Study-720124b9661c40b98805429142401f4a -->

<ul>
  <li>Software</li>
  <ul>
    <li>System Software</li>
    <ul>
      <li>OS</li>

      <li>Language Processor</li>
      <ul>
        <li>Compiler</li>
        <li>Interpreter</li>
        <li>Virtual Machine</li>
      </ul>

      <li>Middleware</li>
      <ul>
        <li>DBMS(MySQL, PostgreSQL, MongoDB, etc...)</li>
        <li>TCP/IP Software</li>
        <li>HTTP Server(Nginx, Apache HTTP Server)</li>
      </ul>
    </ul>

    <li>Application Software</li>
    <ul>
      <li>Web Application</li>
      <li>Mobile Application</li>
      <li>Cross Platform Application</li>
      <li>CLI Tools</li>
      <li>Others</li>
    </ul>
  </ul>

  <li>Hardware</li>
  <ul>
    <li>CPU(processor, micro processor)</li>
    <li>Storage Unit</li>
    <li>Input Unit</li>
  </ul>
</ul>
